import { Button } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Web3 from "web3";
declare let window: any;

const Home: NextPage = () => {
  const [isWeb3, setIsWeb3] = useState(false);
  let web3: Web3 = new Web3();

  let handleConnect = async () => {
    if (typeof window.ethereum !== "undefined") {
      console.log("MetaMask is installed!");
      web3 = new Web3(window.ethereum);
      let connect = await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      console.log(connect);
    }
  };

  let handleDisconnect = async () => {
    window.ethereum;
  };

  let handleBalance = async () => {};

  let handleChangeAccount = async () => {};

  return (
    <div>
      <Head>
        <title>Coin watch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        m="5"
        onClick={() => {
          handleConnect();
        }}
      >
        Connect
      </Button>
      {/* <footer>
        <a>
          Powered by CoinGecko
          <span></span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
