import { Button, ButtonProps } from "@chakra-ui/button";
import { ReactJSXElement } from "@emotion/react/types/jsx-namespace";
import type { NextPage } from "next";
import Head from "next/head";
import Navigation from "../components/Navigation";
import { Link, Img } from "@chakra-ui/react";
import { ArrowForwardIcon, ExternalLinkIcon } from "@chakra-ui/icons";
import { Box, Flex, Heading, Stack, StackItem, Text } from "@chakra-ui/layout";
import ethplorer from "../public/ethplorer.png";
import metamask from "../public/metamask.png";

import Image from "next/image";

const Home: NextPage = () => {
  const LinkToApp = (): ReactJSXElement => {
    return (
      <Link href="/wallet">
        <Button border="1px" rightIcon={<ArrowForwardIcon />}>
          <a>Web app</a>
        </Button>
      </Link>
    );
  };
  return (
    <div>
      <Head>
        <title>Coin Balance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        bg="whitesmoke"
        direction="column"
        justify={{ base: "center", md: "space-around", xl: "space-between" }}
        h={["auto", "auto", "auto", "100vh"]}
      >
        {/* NAVIGATION */}
        <Navigation rightFunc={<LinkToApp />} />
        {/* BODY */}
        <Flex
          h="auto"
          mx="8"
          minHeight="70vh"
          direction={["column", "row"]}
          boxShadow="rgb(218 218 222) 6px 6px 12px, rgb(255 255 255) -6px -6px 12px"
          borderRadius="xl"
        >
          <Box h="100%" w={["100%", "50vw"]}>
            <Box display="flex" flexDirection="column" mx={["4", "8"]}>
              <Heading fontSize={["4xl", "5xl", "6xl", "8xl"]} p="4">
                Coin Balance
              </Heading>
              <Text
                py="4"
                fontSize={["md", "md", "lg", "xl"]}
                marginTop={["0", "12"]}
                p="4"
              >
                Powered by Metamask and Ethplorer, Coin balance will let you see
                the market data of the coins you hold, see what the trending
                coins that are currently being checked out and a display of your
                portfolio allocation.
                <br /> Be sure to be on the Ethereum Network to use this app!
                <br />
                <br />
                You can download Metamask{" "}
                <Link href="https://metamask.io/">
                  here!
                  <ExternalLinkIcon boxSize="4" />
                </Link>
                <Box py="8">
                  <Button variant="ghost">Front end</Button>
                  <Button variant="ghost">Back end</Button>
                </Box>
                <Text fontSize="sm">
                  No user data has been stored on the database, only website
                  analytics are stored.
                </Text>
              </Text>
            </Box>
          </Box>
          <Box h="100%" w={["100%", "50vw"]} p={"8"}>
            <Box w="100%" h="100%">
              <Img borderRadius="xl" src="ethArt.png" boxSize={"100%"} />
            </Box>
          </Box>
        </Flex>
        <Box>
          <Flex direction="row" justify="center" py="4">
            <Box px="2">
              <Image
                src={metamask}
                layout="fixed"
                alt="Icon"
                width="32px"
                height="32px"
              />
            </Box>
            <Box px="4">
              <Image
                src={ethplorer}
                layout="intrinsic"
                alt="ethplorer-logo"
                height="32px"
              />
            </Box>
          </Flex>
        </Box>
        {/* FOOTER */}
      </Flex>
    </div>
  );
};

export default Home;
